### ISSUE TITLE
Relay UDP socket: {:active, true} is not an option for a production system

### ISSUE THREAD

**Issue by erszcz** [esl/MongooseICE#38]
See lib/fennec/evaluator/allocate/request.ex and search for `:gen_udp.open`.

It's not an option for a production system due to the risk of uncontrolled process message queue flooding by the peers. Especially in this case, since the single process in Fennec corresponds to multiple TURN peers.

**Comment by rslota** [comment]
Fixed by #50 . This still may need some tweaking, but this is matter to tackle after we prepare and run proper load tests.
