### ISSUE TITLE
not able to install : urgent

### ISSUE THREAD

**Issue by sandy5487** [esl/MongooseICE#55]
Hello all I have installed mongoseIM 2.0 successfully and using it now I need to implement audio/video call in my application, but installing the MongooseICE is too complex or there no such simple doc to get better knowledge.

Please help me in installing the MongooseICE, I am using ubuntu 16 on my server.

Thanks in advance

**Comment by arkgil** [comment]
Hi @sandy5487 :)

The easiest way to run MongooseICE is by using the prebuilt Docker image. You can find the instructions in the [README](https://github.com/esl/MongooseICE#installation-as-standalone-service). If you don't know Docker, you can learn more about it using its [official documentation](https://docs.docker.com/).

But to make things clear for you - MongooseICE itself is not enough to enable audio and video calls in your application. MongooseICE is a STUN/TURN server - it helps two clients to enable peer-to-peer communication without using intermediate server (STUN), or by relaying data through dedicated server (TURN). You can read more about these concepts in [this article](https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/#after-signaling-using-ice-to-cope-with-nats-and-firewalls). For audio and video calls you would also need a signalling layer (which might be XMPP [Jingle](https://xmpp.org/extensions/xep-0166.html) extension), streaming protocol, and more. You can take a look at [WebRTC](https://webrtc.org/) which aims to be the standard for the audio/video streaming for the web.

Oh, and there is no need to mark issues as urgent - we try to respond as fast as possible 🙂 .

**Comment by arkgil** [comment]
@sandy5487 Did my response make things clearer for you? Let me know if you have any more questions.

**Comment by sandy5487** [comment]
@arkgil Thanks for the knowledge sharing and yes am clear about the process now. But I am stuck also for implementing audio/video call.

Let me know if you can help me by any chance.

Thanks again

**Comment by arkgil** [comment]
@sandy5487 Unfortunately we haven't completely figured it out yet. If we do, the implementation will most probably be open source, so keep an eye on our repos/social channels 🙂

**Comment by arkgil** [comment]
I'll close this for now - just reopen the issue if you have any more question 🙂
