### ISSUE TITLE
MongooseICE  with ejabberd

### ISSUE THREAD

**Issue by naemakram** [esl/MongooseICE#56]
Hi 
I am using ejabberd now I wanted to integrate the MongooseICE  in it , can any one please help me how I can achieve that.

**Comment by arkgil** [comment]
Hi @naemakram! 🙂 Could you please explain what are you trying to achieve? Currently MongooseICE is only a STUN/TURN server which allows simple P2P communication between 2 endpoints. We haven't figured out an easy way to set up audio and video calls by using it, yet.

**Comment by arkgil** [comment]
@naemakram I'm closing the issue for now - just reopen it in case you have some input on the topic.
