### ISSUE TITLE
how to configure MongooseICE without docker

### ISSUE THREAD

**Issue by zaidshaikh112** [esl/MongooseICE#57]
please help me with open detail of mongooseICE configuration on server i am using ubuntu 16.04 and postgres 9.5 databases for mongooseIM 

Thanks for your support in advance

**Comment by arkgil** [comment]
Hi @zaidshaikh112! 

Could you please describe what are you trying to achieve using MongooseICE?

As I've already explained in #56 and #55, currently MongooseICE is only a simple STUN/TURN server, and there is no easy way to set up audio and video calls with it, yet. Unless you're trying to achieve something else, I'm afraid I won't be able to help you.

If you need help with with setting up MongooseIM please refer to [official documentation](http://mongooseim.readthedocs.io) or ask a question on esl/MongooseIM issue tracker 🙂

**Comment by zaidshaikh112** [comment]
i need to configure  MongooseICE (ICE/TURN/STUN server) with MongooseIM  2.1.0 server and i dont want easy step for configure just i want to install  MongooseICE (ICE/TURN/STUN server)  without docker. & thanks arkgil for your fast reply i want just documentation but without docker

**Comment by arkgil** [comment]
[Here](https://github.com/esl/MongooseICE#building-and-using-a-release) are the instructions for building a non-Docker release of MongooseICE. 

After you've built the release, you can start it in the foreground using
```
$ _build/prod/rel/mongooseice/bin/mongooseice foreground
```

or in the background
```
$ _build/prod/rel/mongooseice/bin/mongooseice start
```

You can configure it using environment variables, as described [here](https://github.com/esl/MongooseICE#configuration). 

But to be honest, I'd reconsider using Docker (if that's possible for you) - it's much simpler and less error-prone.
