### ISSUE TITLE
inet_parse:~p:~p: erroneous line, skipped~n "/etc/resolv.conf"

### ISSUE THREAD

**Issue by shubham1164** [esl/MongooseICE#62]
I want to set up MongooseimICE on Raspberry PI with Raspbian OS. 

I have build from the source code and it builds successfully.
`$MIX_ENV=prod mix do deps.get, docker.build, docker.release`

When I tried to run it with 
`$_build/prod/rel/mongooseice/bin/mongooseice console`

it shows the below logs:
```
2019-04-03 07:33:02 inet_parse:~p:~p: erroneous line, SKIPPED~n
	"/etc/resolv.conf"
	3
Erlang/OTP 19 [erts-8.2.1] [source] [smp:4:4] [async-threads:10] [kernel-poll:false]


=INFO REPORT==== 3-Apr-2019::08:33:02 ===
inet_parse:"/etc/resolv.conf":3: erroneous line, SKIPPED

07:33:02.388 [info]  Starting STUN/TURN server (127.0.0.1:3478) with relay_ip: 127.0.0.1
Interactive Elixir (1.4.5) - press Ctrl+C to exit (type h() ENTER for help)
iex(mongooseice@127.0.0.1)1> 
```
Concerns:
1. What is the error inet_parse about and
2. Where to set general and UDP configuration?

My guess is error is due to config missing, please advice

**Comment by rslota** [comment]
Hi @shubham1164 ,

> 1. What is the error inet_parse about

The error you're seeing does not seem to come from MongooseICE itself. It seems to be an error from Erlang's `inet` application indicating it detected error in you `/etc/resolv.conf` configuration. Depending on what it actually is, it may / may not be problematic.

> 2. Where to set general and UDP configuration?

Can you give example of the configuration you have in mind?

**Comment by shubham1164** [comment]
Thanks for the help, I am not using the VOIP module anymore.
