### ISSUE TITLE
Do I need separate SIP system like routr.io to make VOIP work with MongooseIM

### ISSUE THREAD

**Issue by shubham1164** [esl/MongooseICE#63]
I am using MongooseIM with PostgreSQL as backend (for users). Now I want to add Voice calling (VOIP) support using MongooseIM and MongooseimICE. Following are the concerns:

1. Do I need to use a separate module like www.routr.io for SIP, or is it possible to do it with Mongooseim + MongooseimICE alone?
2. In the Mongooseim - jingle + routr.io tutorial, I can successfully create a voice call by following the tutorial. If I can do voice call with routr.io, then can I skip the MongooseimICE completely?

**Comment by rslota** [comment]
Hi @shubham1164 ,

**Comment by shubham1164** [comment]
Thanks for the help, I am not using the VOIP module anymore.
